In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

In [ ]:
Dataset=pd.read_csv('diabetes.csv')

In [ ]:
Dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [ ]:
Dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [ ]:
pd.read_csv?

In [ ]:
Dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [ ]:
Dataset.shape

(768, 9)

In [ ]:
Dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [ ]:
Dataset['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

0-> Non Diabetic
1-> Diabetic

In [ ]:
Dataset.groupby('Outcome').mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [ ]:
Dataset.groupby('Glucose').mean()

Pregnancies  BloodPressure  SkinThickness     Insulin        BMI  \
Glucose                                                                     
0           2.800000      67.600000      29.600000    4.600000  32.880000   
44          5.000000      62.000000       0.000000    0.000000  25.000000   
56          2.000000      56.000000      28.000000   45.000000  24.200000   
57          4.500000      70.000000      18.500000    0.000000  27.250000   
61          3.000000      82.000000      28.000000    0.000000  34.400000   
...              ...            ...            ...         ...        ...   
195         6.500000      70.000000      16.500000   72.500000  28.000000   
196         5.333333      80.666667      21.666667  176.333333  37.933333   
197         4.000000      71.000000      45.750000  321.750000  31.950000   
198         0.000000      66.000000      32.000000  274.000000  41.300000   
199         1.000000      76.000000      43.000000    0.000000  42.900000   

         DiabetesPedigreeFunction        Age  Outcome  
Glucose                                                
0                        0.380200  28.600000     0.40  
44                       0.587000  36.000000     0.00  
56                       0.332000  22.000000     0.00  
57                       0.415500  54.000000     0.00  
61                       0.243000  46.000000     0.00  
...                           ...        ...      ...  
195                      0.245500  43.000000     1.00  
196                      0.643667  42.333333     1.00  
197                      1.063250  46.250000     0.75  
198                      0.502000  28.000000     1.00  
199                      1.394000  22.000000     1.00  

[136 rows x 8 columns]

Separating the data and labels

In [ ]:
X=Dataset.drop(columns='Outcome',axis=1) #axis is 1 means we are droping the column
Y=Dataset['Outcome']

In [ ]:
print(X)
print(Y)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


Normalization of data so that we have the values in between 0,1 for better prediction

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(X)

StandardScaler()

In [ ]:
StandardScaler?

In [ ]:
Standardized_data=scaler.transform(X)

In [ ]:
Standardized_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [ ]:
X=Standardized_data
Y=Dataset['Outcome']

In [ ]:
print(X)
print(Y)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


Splitting the data into training and testing

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=2)

In [ ]:
X_train

array([[-1.14185152, -0.05929342, -3.57259724, ...,  0.05170968,
        -0.9992857 , -0.78628618],
       [ 0.63994726, -0.49745345,  0.04624525, ..., -0.15136112,
        -1.05666795,  0.31985461],
       [-0.84488505,  2.13150675, -0.47073225, ..., -0.24020459,
        -0.2231152 ,  2.19178518],
       ...,
       [ 2.12477957, -1.12339636,  0.25303625, ..., -0.24020459,
        -0.51908683,  0.14967911],
       [ 0.04601433, -0.27837344,  0.45982725, ...,  0.94014439,
        -0.71237443,  0.40494237],
       [-1.14185152, -1.09209922, -0.05715025, ...,  0.48323511,
        -0.70633419, -0.70119842]])

In [ ]:
X_test

array([[-0.25095213, -0.46615631,  0.14964075, ..., -0.78595734,
        -0.79995787, -0.53102292],
       [-0.25095213, -0.24707629, -1.29789624, ..., -1.21748278,
        -1.00230582, -0.95646168],
       [ 0.3429808 ,  0.81702665,  0.45982725, ...,  0.2167047 ,
        -0.76673656,  2.7023117 ],
       ...,
       [-0.54791859, -0.34096773,  0.25303625, ...,  0.05170968,
         0.6829204 , -0.53102292],
       [-0.54791859, -1.24858494,  0.14964075, ..., -0.24020459,
         0.22688248, -0.70119842],
       [ 2.7187125 , -0.46615631,  0.14964075, ...,  0.58477051,
        -0.88754131,  1.00055664]])

In [ ]:
print(X.shape, X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)


Training The Model

In [ ]:
classifier=svm.SVC(kernel='linear')

In [ ]:
#training the svm model
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

MODEL EVALUATION

ACCURACY SCORE OF TRAINING DATA

In [ ]:
X_train_prediction=classifier.predict(X_train)

In [ ]:
X_train_prediction

array([0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,

In [ ]:
training_data_accuracy=accuracy_score(X_train_prediction,Y_train)

In [ ]:
print("Accuracy score of our training data is:",training_data_accuracy)

Accuracy score of our training data is: 0.7866449511400652


ACCURACY SCORE OF TESTING DATA

In [ ]:
X_test_prediction=classifier.predict(X_test)

In [ ]:
testing_data_accuracy=accuracy_score(X_test_prediction,Y_test)

In [ ]:
print("Accuracy score of testing data is:", testing_data_accuracy)

Accuracy score of testing data is: 0.7727272727272727


MAKING A PREDICTIVE SYSTEM

In [ ]:
input_data=(4,110,92,0,0,37.6,0.191,30)

input_data_as_numpy_array=np.asarray(input_data)

input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

std_data=scaler.transform(input_data_reshaped)

prediction=classifier.predict(std_data)
print(prediction)

if(prediction[0]==0):
  print("The person is not diabetic")
else:
  print("The person is diabetic")

[0]
The person is not diabetic


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
input_data=(6,148,72,35,0,33.6,0.627,50)

input_data_as_numpy_array=np.asarray(input_data)

input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

std_data=scaler.transform(input_data_reshaped)

prediction=classifier.predict(std_data)
print(prediction)

if(prediction[0]==0):
  print("The person is not diabetic")
else:
  print("The person is diabetic")

[1]
The person is diabetic


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:

# Function to predict diabetes
def predict_diabetes(input_data):
    input_data = [float(x) for x in input_data.split(',')]
    input_data_features = scaler.transform([input_data])

    prediction = classifier.predict(input_data_features)

    return "Non diabetic" if prediction[0] == 1 else "diabetic"

# CLI interface
if __name__ == "__main__":
    print("Welcome to the diabetes prediction system!")
    while True:
        user_input = input("Enter the patient record here (or type 'exit' to quit):\n")
        if user_input.lower() == 'exit':
            break
        result = predict_diabetes(user_input)
        print(f"Prediction: {result}\n")

Welcome to the diabetes prediction system!
Enter the patient record here (or type 'exit' to quit):
1,85,66,29,0,26.6,0.351,31


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Prediction: diabetic

Enter the patient record here (or type 'exit' to quit):
7,196,90,0,0,39.8,0.451,41


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Prediction: Non diabetic

Enter the patient record here (or type 'exit' to quit):
10,125,70,26,115,31.1,0.205,41


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Prediction: diabetic

